name: Deploy Gitee Pages

on:
  push:
    paths-ignore: 
      - 'README.md'
      - 'scripts/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:Bernankez/BilibiliFans.git
          destination-repo: git@gitee.com:bernankez/bilibili-fans.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: bernankez
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: bernankez/bilibili-fans
          branch: master
