name: Deploy Gitee Pages

on: page_build

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:Bernankez/BilibiliFans.git
          destination-repo: git@gitee.com:bernankez/BilibiliFans.git

      - name: Deploy Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: bernankez
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: bernankez/BilibiliFans
          branch: deploy
